# Generated by Django 5.0.1 on 2024-02-08 17:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManageAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(max_length=255, null=True, upload_to='assets/')),
                ('condition_type', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('regular', 'Regular')], default=None, max_length=100, null=True)),
                ('assets_type', models.CharField(choices=[('accessories', 'Accessories'), ('other', 'Other')], default=None, max_length=100, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('assigned_Id', models.CharField(blank=True, max_length=10, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=32, null=True)),
                ('assigned_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_assigned_by', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_assigned_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
