# Generated by Django 5.0.1 on 2024-02-08 17:38

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('max_leaves', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LeaveStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveBalence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_balance', models.FloatField(default=0)),
                ('user', models.ForeignKey(limit_choices_to={'groups__name': 'Employee'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('leave_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave.leavecategory')),
            ],
            options={
                'unique_together': {('user', 'leave_category')},
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('is_start_date_half_day', models.BooleanField(default=False)),
                ('end_date', models.DateField()),
                ('is_end_date_half_day', models.BooleanField(default=False)),
                ('reason', models.TextField()),
                ('requested_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('notes', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.leavebalence')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leave.leavecategory')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.leavestatus')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='leave.type')),
            ],
        ),
    ]
